{"uuid":"45e11b0b-38c7-4ee4-b714-38986c233374","name":"11. should handle or throw an error when the limit is Infinity","historyId":"0e5bd35c39bb78351a82157ec03ccd69:d41d8cd98f00b204e9800998ecf8427e","status":"passed","statusDetails":{},"stage":"finished","steps":[],"attachments":[],"parameters":[],"labels":[{"name":"language","value":"javascript"},{"name":"framework","value":"jest"},{"name":"package","value":"functionsUnittests.arrayFunctionsUnittests.generatePrimes.test.ts"},{"name":"host","value":"pkrvmfkh1xnbeme"},{"name":"thread","value":"3"},{"name":"parentSuite","value":"generatePrimes"}],"links":[],"start":1752001512182,"fullName":"functionsUnittests/arrayFunctionsUnittests/generatePrimes.test.ts#generatePrimes 11. should handle or throw an error when the limit is Infinity","testCaseId":"0e5bd35c39bb78351a82157ec03ccd69","stop":1752001512185}